<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<title>Dynamic breaking resistor in Chennai | Power Resistor in Chennai</title>
<link rel="canonical" href="https://nationalswitchgears.com/product/dynamic-breaking-resistor" />
<meta content="width=device-width, initial-scale=1.0" name="viewport">
<meta content="Dynamic breaking resistor,Dynamic breaking resistor in chennai,Dynamic breaking resistor in india,Dynamic breaking resistor in dubai,Dynamic breaking resistor manufacture,best price Dynamic breaking resistor, lowest price Dynamic breaking resistor" name="keywords">
<meta content="Looking for top-quality dynamic breaking resistors or power resistors in Chennai? Explore our wide range of products, trusted by industry professionals. Contact us today!" name="description">
      <!-- Stylesheets -->
<link href="<?php echo WEB_DIR?>public/css/bootstrap.css" rel="stylesheet">
<link href="<?php echo WEB_DIR?>public/css/style.css" rel="stylesheet">
<link href="<?php echo WEB_DIR?>public/css/responsive.css" rel="stylesheet">
<link href="https://fonts.googleapis.com/css2?family=Roboto:wght@300;400;500;700;900&display=swap" rel="stylesheet">
<link href="https://fonts.googleapis.com/css2?family=Fira+Sans:wght@300;400;500;600;700;800;900&display=swap" rel="stylesheet">
<link rel="shortcut icon" href="images/favicon.png" type="image/x-icon">
<link rel="icon" href="<?php echo WEB_IMG ?>favicon.ico" type="image/x-icon">
<!-- Responsive -->
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0">
<!-- Google tag (gtag.js) -->
<script async src="https://www.googletagmanager.com/gtag/js?id=G-LC7N1ZZDYC"></script>
   <script>
   window.dataLayer = window.dataLayer || [];
   function gtag(){dataLayer.push(arguments);}
   gtag('js', new Date());

   gtag('config', 'G-LC7N1ZZDYC');
   </script>
   <style>
      ol li{
         list-style-type: none;
      }
		.refresh {
			display: inline-block;
			transform: rotate(90deg);
			font-size: 22px;
    		color: white;
		}
   </style>
</head>
<body> 
<div class="page-wrapper">
	
    <!-- Preloader -->
    <div class="preloader"></div>
	<!-- End Preloader -->
 	<?= view('home_header'); ?> 
    <!-- End Main Header -->
	

	<!-- Page Title -->
    <section class="page-title" style="background-image:url(<?php echo WEB_IMG ?>background/dynamic.jpg)">
        <div class="auto-container">
			<h2>Dynamic breaking resistor</h2>
			<ul class="bread-crumb clearfix">
				<li><a href="<?php echo WEB_URL?>">Home</a></li>
				<li>Dynamic breaking resistor</li>
			</ul>
        </div>
    </section>
    <!-- End Page Title -->
	
	<!-- Sidebar Page Container -->
    <div class="sidebar-page-container">
    	<div class="auto-container">
        	<div class="row clearfix">
				
				<!-- Sidebar Side -->
                <div class="sidebar-side left-sidebar col-lg-4 col-md-12 col-sm-12">
                	<aside class="sidebar">
						<!-- Sidebar Widget -->
						<div class="sidebar-widget category-widget">
							<ul class="cat-list">
								<li><a href="<?php echo WEB_URL?>product/neutral-grounding-resistor">Neutral Grounding Resistor</a></li>
								<li><a href="<?php echo WEB_URL?>product/load-bank">Load Bank</a></li>
								<li><a href="<?php echo WEB_URL?>product/harmonic-filter-resistor">Harmonic Filter Resistor</a></li>
								<li><a href="<?php echo WEB_URL?>product/switch-disconnector">Switch Disconnector</a></li>
								<li class="active"><a href="<?php echo WEB_URL?>product/dynamic-breaking-resistor">Dynamic Breaking Resistor</a></li>
							</ul>
						</div>
						
						<!-- Contact Widget -->
						<div class="sidebar-widget contact-widget">
							<div class="widget-content" style="background-image:url(<?php echo WEB_IMG ?>background/national-contact-us.png)">
							<div class="about-phone_box">
								<span class="about-phone_icon fa-solid fa-phone fa-fw"></span>
								<span style="color:white;">Contact Us</span> <br>
								<a class="about-two_phone-number" style="color:white;"  href="tel:+91 97910 04074/5">+91 44 26254432</a>
							</div>
							</div>
						</div>
						
					</aside>
				</div>
				
				<!-- Content Side -->
                <div class="content-side right-sidebar col-lg-8 col-md-12 col-sm-12">
					<div class="service-detail">
						<div class="inner-box">
							<div class="image">
								<img src="<?php echo WEB_IMG ?>gallery/dynamic-breaking-resistor.jpg" alt="dynamic breaking resistor"  title="Dynamic braking resistors are used in motor control systems to dissipate excess energy generated by the motor when it's decelerating or coming to a stop. This energy is typically fed back into the system and can cause voltage spikes or other issues if not properly managed."/>
							</div>
							<h3 class="sec-title_heading"><span>Dynamic breaking resistor / Power Resistor</span></h3>

							<p>The applications are innumerable like starting of slip ring Induction motor / Voltage dropping Resistor / Dynamic Braking Resistor for DC Motors / Traction Duty Resistors for Railways etc.,</p>
								 <h5 class="sec-title_heading"><span>Technical Specification:</span></h5>
								<ul>
									<li style="list-style:inside;">Degree of protection : IP00 / IP 23</li>
									<li style="list-style:inside;">Service : Indoor / Outdoor</li>
									<li style="list-style:inside;">Enclosure Finishing : Epoxy powder coat painted / Galvanized</li>
									<li style="list-style:inside;">Mounting type : Floor / Steel Structure Mounted</li>
									<li style="list-style:inside;">Data required for design : Resistance value, Discharge / Braking Duration/ Current vs. Time curve, Insulation Voltage, Degree of Protection, Duty Cycle / Duty Factor</li>
									<li style="list-style:inside;">Standard followed : BS587</li>
									<li style="list-style:inside;">Resistive Element : Stainless steel / Fecral</li>
									<li style="list-style:inside;">Application : Starting slip Ring Induction motor in Cranes / Pumps / Winches etc</li>
								</ul>	
								
							<div class="row clearfix">
								
								<!-- Feature Two -->
								<div class="feature-two col-lg-12 col-md-12 col-sm-12">
									<div class="feature-two_inner">
										<div class="feature-two_content">
											<span class="feature-two_icon"><img src="<?php echo WEB_IMG ?>icons/feature-6.png" alt="" /></span>
											<h5 class="feature-two_heading">Why <span>National Switchgears?</span></h5>
											<div class="feature-two_text">National Switchgears was founded with very purpose of manufacturing high quality resistor for various industrial and research applications in India.</div>
										</div>
									</div>
								</div>
								
								
							</div>
							
							<div class="row clearfix">
								<!-- Column -->
								<div class="column col-lg-6 col-md-6 col-sm-12">
									<div class="image">
										<img src="<?php echo WEB_IMG ?>resource/national-switchgear-customer-value.jpg" alt="customer" />
									</div>
								</div>
								<!-- Column -->
								<div class="column col-lg-6 col-md-6 col-sm-12">
									<h4>We serve the best work</h4>
									<p>We are the first company to export NGR from India. Almost all leading consultants in India and well known consulting firms in abroad have approved our NGR.</p>
								</div>
							</div>
							
							<div class="feature-lower_box">
								<div class="row clearfix">
									
									<!-- Feature Three -->
									<div class="feature-three col-lg-4 col-md-4 col-sm-6">
										<div class="feature-three_inner">
											<span class="feature-three_icon"><img src="<?php echo WEB_IMG ?>icons/service-35.png" alt="" /></span>
											Best quality
										</div>
									</div>
									<div class="feature-three col-lg-4 col-md-4 col-sm-6">
										<div class="feature-three_inner">
											<span class="feature-three_icon"><img src="<?php echo WEB_IMG ?>icons/service-37.png" alt="" /></span>
											Best Price
										</div>
									</div>
									
									<!-- Feature Three -->
									<div class="feature-three col-lg-4 col-md-4 col-sm-6">
										<div class="feature-three_inner">
											<span class="feature-three_icon"><img src="<?php echo WEB_IMG ?>icons/service-36.png" alt="" /></span>
											Best Support
										</div>
									</div>
									
									<!-- Feature Three -->
									
								</div>
							</div>
							
						</div>
					</div>
				</div>
				
			</div>
		</div>
	</div>
	<!-- End Sidebar Page Container -->
	<!-- Footer -->
	<?= view('footer'); ?>
	<!-- End Footer -->
	
</div>
<!-- End PageWrapper -->


<!-- Scroll To Top -->
<div class="scroll-to-top scroll-to-target" data-target="html"><span class="fa fa-angle-double-up"></span></div>

<script src="<?php echo WEB_DIR?>public/js/jquery.js"></script>
<script src="<?php echo WEB_DIR?>public/js/appear.js"></script>
<script src="<?php echo WEB_DIR?>public/js/owl.js"></script>
<script src="<?php echo WEB_DIR?>public/js/wow.js"></script>
<script src="<?php echo WEB_DIR?>public/js/odometer.js"></script>
<script src="<?php echo WEB_DIR?>public/js/mixitup.js"></script>
<script src="<?php echo WEB_DIR?>public/js/popper.min.js"></script>
<script src="<?php echo WEB_DIR?>public/js/parallax.min.js"></script>
<script src="<?php echo WEB_DIR?>public/js/bootstrap.min.js"></script>
<script src="<?php echo WEB_DIR?>public/js/tilt.jquery.min.js"></script>
<script src="<?php echo WEB_DIR?>public/js/magnific-popup.min.js"></script>

<script src="<?php echo WEB_DIR?>public/js/script.js"></script>

<!--[if lt IE 9]><script src="https://cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.3/html5shiv.js"></script><![endif]-->
<!--[if lt IE 9]><script src="public/js/respond.js"></script><![endif]-->

</body>
</html>
