<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<title>Harmonic Filter Resistor in Chennai | National Switchgears</title>
<link rel="canonical" href="https://nationalswitchgears.com/product/harmonic-filter-resistor" />
<meta content="width=device-width, initial-scale=1.0" name="viewport">
<meta content="Harmonic filter resistor, resistors for harmonic filters,best price Harmonic filter resistor, Harmonic filter resistor in chennai, Harmonic filter resistor in india, Harmonic filter resistor in dubai" name="keywords">
<meta content="Click for industrial harmonic filter resistor solutions in Chennai. Explore specialized options designed to meet the rigorous demands of industrial setup configurations." name="description">
   
<!-- Stylesheets -->
<link href="<?php echo WEB_DIR?>public/css/bootstrap.css" rel="stylesheet">
<link href="<?php echo WEB_DIR?>public/css/style.css" rel="stylesheet">
<link href="<?php echo WEB_DIR?>public/css/responsive.css" rel="stylesheet">
<link href="https://fonts.googleapis.com/css2?family=Roboto:wght@300;400;500;700;900&display=swap" rel="stylesheet">
<link href="https://fonts.googleapis.com/css2?family=Fira+Sans:wght@300;400;500;600;700;800;900&display=swap" rel="stylesheet">
<link rel="shortcut icon" href="images/favicon.png" type="image/x-icon">
<link rel="icon" href="<?php echo WEB_IMG ?>favicon.ico" type="image/x-icon">
<!-- Responsive -->
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0">
<!-- Google tag (gtag.js) -->
<script async src="https://www.googletagmanager.com/gtag/js?id=G-LC7N1ZZDYC"></script>
   <script>
   window.dataLayer = window.dataLayer || [];
   function gtag(){dataLayer.push(arguments);}
   gtag('js', new Date());

   gtag('config', 'G-LC7N1ZZDYC');
   </script>
   <style>
      ol li{
         list-style-type: none;
      }
		.refresh {
			display: inline-block;
			transform: rotate(90deg);
			font-size: 22px;
    		color: white;
		}
   </style>
</head>
<body> 
<div class="page-wrapper">
	
    <!-- Preloader -->
    <div class="preloader"></div>
	<!-- End Preloader -->
 	<?= view('home_header'); ?> 
    <!-- End Main Header -->
	

	<!-- Page Title -->
    <section class="page-title" style="background-image:url(<?php echo WEB_IMG ?>background/harmoinc.jpg)">
        <div class="auto-container">
			<h2>Harmonic Filter Resistor</h2>
			<ul class="bread-crumb clearfix">
				<li><a href="<?php echo WEB_URL?>home">Home</a></li>
				<li>Harmonic Filter Resistor</li>
			</ul>
        </div>
    </section>
    <!-- End Page Title -->
	
	<!-- Sidebar Page Container -->
    <div class="sidebar-page-container">
    	<div class="auto-container">
        	<div class="row clearfix">
				
				<!-- Sidebar Side -->
                <div class="sidebar-side left-sidebar col-lg-4 col-md-12 col-sm-12">
                	<aside class="sidebar">
						<!-- Sidebar Widget -->
						<div class="sidebar-widget category-widget">
							<ul class="cat-list">
								<li><a href="<?php echo WEB_URL?>product/neutral-grounding-resistor">Neutral Grounding Resistor</a></li>
								<li><a href="<?php echo WEB_URL?>product/load-bank">Load Bank</a></li>
								<li class="active"><a href="<?php echo WEB_URL?>product/harmonic-filter-resistor">Harmonic Filter Resistor</a></li>
								<li><a href="<?php echo WEB_URL?>product/switch-disconnector">Switch Disconnector</a></li>
								<li><a href="<?php echo WEB_URL?>product/dynamic-breaking-resistor">Dynamic Breaking Resistor</a></li>
							</ul>
						</div>
						
						<!-- Contact Widget -->
						<div class="sidebar-widget contact-widget">
							<div class="widget-content" style="background-image:url(<?php echo WEB_IMG ?>background/national-contact-us.png)">
							<div class="about-phone_box">
								<span class="about-phone_icon fa-solid fa-phone fa-fw"></span>
								<span style="color:white;">Contact Us</span> <br>
								<a class="about-two_phone-number" style="color:white;"  href="tel:+91 97910 04074/5">+91 44 26254432</a>
							</div>
							</div>
						</div>
						
					</aside>
				</div>
				
				<!-- Content Side -->
                <div class="content-side right-sidebar col-lg-8 col-md-12 col-sm-12">
					<div class="service-detail">
						<div class="inner-box">
							<div class="image">
								<img src="<?php echo WEB_IMG ?>gallery/harmonic-filter-resistor.jpg" alt="harmonic filter resistor" title="Harmonic filter resistors are components used in power systems to dampen and mitigate the effects of harmonic currents generated by non-linear loads, such as variable frequency drives, computers, and other electronic equipment."/>
							</div>
							<h3 class="sec-title_heading"><span>Harmonic Filter Resistor</span></h3>

							<p>Ever increasing usage of solid state devices like VFD drives and Thyristor controlled Electrical Furnaces etc causes distortion of waveforms with higher frequency Harmonics in supply system resulting in poor quality of power to end users. Harmonic filters are designed to bypass unwanted frequencies using combination of Reactor, Capacitors along with Resistor to achieve better quality power. We specialize in manufacturing medium voltage Filter Resistors for various applications starting from 11 kV onwards.</p>
								 <h5 class="sec-title_heading"><span>Technical Specification:</span></h5>
								<ul>
									<li style="list-style:inside;">Range : Up to 132 kV</li>
									<li style="list-style:inside;">Degree of protection : IP 23 made suitable for outdoor</li>
									<li style="list-style:inside;">Service : Outdoor</li>
									<li style="list-style:inside;">Enclosure Finishing : Galvanized / Stainless steel / Epoxy powder coat painted</li>
									<li style="list-style:inside;">Mounting type : Each phase Resistor mounted on standoff Insulator&stacked one above the other For 3 Phase configuration/Steel Structure Mounted</li>
									<li style="list-style:inside;">Voltage : Up to 36 kV</li>
									<li style="list-style:inside;">Standard followed : BS587 / IEC 60060</li>
									<li style="list-style:inside;">Standard followed : IEEE - 32</li>
									<li style="list-style:inside;">Max. Power Dissipation : Up to 2MW</li>
									<li style="list-style:inside;">Resistive elements : Stainless steel AISI 304 / Fecral (Al-Cr steel)</li>
									<li style="list-style:inside;">Maximum BIL : 400 kV</li>
									<li style="list-style:inside;">Design : Live tank or Earthed tank design</li>
									<li style="list-style:inside;">Normal creepage of porcelain insulator : 25mm/kV</li>
								</ul>	
								
							<div class="row clearfix">
								
								<!-- Feature Two -->
								<div class="feature-two col-lg-12 col-md-12 col-sm-12">
									<div class="feature-two_inner">
										<div class="feature-two_content">
											<span class="feature-two_icon"><img src="<?php echo WEB_IMG ?>icons/feature-6.png" alt="" /></span>
											<h5 class="feature-two_heading">Why <span>National Switchgears?</span></h5>
											<div class="feature-two_text">National Switchgears was founded with very purpose of manufacturing high quality resistor for various industrial and research applications in India.</div>
										</div>
									</div>
								</div>
								
								
							</div>
							
							<div class="row clearfix">
								<!-- Column -->
								<div class="column col-lg-6 col-md-6 col-sm-12">
									<div class="image">
										<img src="<?php echo WEB_IMG ?>resource/national-switchgear-customer-value.jpg" alt="customer" />
									</div>
								</div>
								<!-- Column -->
								<div class="column col-lg-6 col-md-6 col-sm-12">
									<h4>We serve the best work</h4>
									<p>We are the first company to export NGR from India. Almost all leading consultants in India and well known consulting firms in abroad have approved our NGR.</p>
								</div>
							</div>
							
							<div class="feature-lower_box">
								<div class="row clearfix">
									
									<!-- Feature Three -->
									<div class="feature-three col-lg-4 col-md-4 col-sm-6">
										<div class="feature-three_inner">
											<span class="feature-three_icon"><img src="<?php echo WEB_IMG ?>icons/service-35.png" alt="" /></span>
											Best quality
										</div>
									</div>
									<div class="feature-three col-lg-4 col-md-4 col-sm-6">
										<div class="feature-three_inner">
											<span class="feature-three_icon"><img src="<?php echo WEB_IMG ?>icons/service-37.png" alt="" /></span>
											Best Price
										</div>
									</div>
									
									<!-- Feature Three -->
									<div class="feature-three col-lg-4 col-md-4 col-sm-6">
										<div class="feature-three_inner">
											<span class="feature-three_icon"><img src="<?php echo WEB_IMG ?>icons/service-36.png" alt="" /></span>
											Best Support
										</div>
									</div>
									
									<!-- Feature Three -->
									
								</div>
							</div>
							
						</div>
					</div>
				</div>
				
			</div>
		</div>
	</div>
	<!-- End Sidebar Page Container -->
	

	<!-- Footer -->
	<?= view('footer'); ?>
	<!-- End Footer -->
	
</div>
<!-- End PageWrapper -->


<!-- Scroll To Top -->
<div class="scroll-to-top scroll-to-target" data-target="html"><span class="fa fa-angle-double-up"></span></div>

<script src="<?php echo WEB_DIR?>public/js/jquery.js"></script>
<script src="<?php echo WEB_DIR?>public/js/appear.js"></script>
<script src="<?php echo WEB_DIR?>public/js/owl.js"></script>
<script src="<?php echo WEB_DIR?>public/js/wow.js"></script>
<script src="<?php echo WEB_DIR?>public/js/odometer.js"></script>
<script src="<?php echo WEB_DIR?>public/js/mixitup.js"></script>
<script src="<?php echo WEB_DIR?>public/js/popper.min.js"></script>
<script src="<?php echo WEB_DIR?>public/js/parallax.min.js"></script>
<script src="<?php echo WEB_DIR?>public/js/bootstrap.min.js"></script>
<script src="<?php echo WEB_DIR?>public/js/tilt.jquery.min.js"></script>
<script src="<?php echo WEB_DIR?>public/js/magnific-popup.min.js"></script>

<script src="<?php echo WEB_DIR?>public/js/script.js"></script>

<!--[if lt IE 9]><script src="https://cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.3/html5shiv.js"></script><![endif]-->
<!--[if lt IE 9]><script src="public/js/respond.js"></script><![endif]-->

</body>
</html>
